#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6741069450                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://cgxoa.app.link/aTIzi23UVRb                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : #https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Family-friendly charades and alias game—no reading required!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Viacheslav Nechyporenko                               
your_link                                 : https://familycharades.com                   
your_city                                 : Space                                
email_address                             : atslavasdad@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Family Fun Gameplay
    description                           : Enjoy a charades & alias game that brings the whole family together for endless fun and laughter!
    fontawesome_icon_name                 : users

  - title                                 : No Reading Required
    description                           : Picture-supported word cards let non-readers jump right in—perfect for the youngest players.
    fontawesome_icon_name                 : child

  - title                                 : Educational Development
    description                           : Boost creativity, communication, and social skills—playful learning for kids and parents alike.
    fontawesome_icon_name                 : brain

  - title                                 : 300+ Words & Multiple Categories
    description                           : Choose from over 300 words across a range of categories to keep every round fresh and exciting.
    fontawesome_icon_name                 : list

  - title                                 : Customizable & Action-Packed
    description                           : Tailor your game with customizable settings and fun action cards that add unique challenges.
    fontawesome_icon_name                 : sliders-h

  - title                                 : Printable Word List
    description                           : Unlock a printable version of all words with an optional subscription for even more ways to play.
    fontawesome_icon_name                 : print

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#cce5e5"                                # Matching black from design system
topbar_transparency                       : 0.9                                      # Increased opacity for better contrast
topbar_title_color                        : "#131313"                               # Matching white from design system

# Add these lines for your custom domain
url: "https://familycharades.com"
enforce_ssl: familycharades.com

cover_image                               : #assets/headerimage.png                    
cover_overlay_color                       : "#F2E6F7"                               # Matching lightPink from design system
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Keeping black device color

body_background_color                     : "#F2E6F7"                               # Matching lightPink background

link_color                                : "#131313"                               # Using darkBlue for links

app_title_color                           : "#131313"                               # Using black for contrast
app_price_color                           : "#131313"                               # Using black for contrast
app_description_color                     : "#131313"                               # Using black for contrast

feature_title_color                       : "#131313"                               # Using black for titles
feature_text_color                        : "#6B8989"                               # Using lightGray for feature text

feature_icons_foreground_color            : "#131313"                               # Using darkYellow for icons
feature_icons_background_color            : "#FFFFFF"                               # Using lightYellow for icon backgrounds

social_icons_foreground_color             : "#131313"                               # Using black for social icons
social_icons_background_color             : "#FFFFFF"                               # Using lightBlue for social icon backgrounds

footer_text_color                         : "#6B8989"                               # Using lightGray for footer text

# Add these lines for proper asset handling
baseurl: ""  # If your site is at the root













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
