name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Create Firebase Config
        run: |
          echo "apiKey: \"${{ secrets.FIREBASE_API_KEY }}\"" > _data/firebase.yml
          echo "authDomain: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"" >> _data/firebase.yml
          echo "projectId: \"${{ secrets.FIREBASE_PROJECT_ID }}\"" >> _data/firebase.yml
          echo "storageBucket: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"" >> _data/firebase.yml
          echo "messagingSenderId: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"" >> _data/firebase.yml
          echo "appId: \"${{ secrets.FIREBASE_APP_ID }}\"" >> _data/firebase.yml
          echo "measurementId: \"${{ secrets.FIREBASE_MEASUREMENT_ID }}\"" >> _data/firebase.yml

      - name: Build site
        run: |
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site 